workflows:
  android-release:
    name: Gauging App Build
    environment:
      java: 17
    scripts:
      - name: Grant gradlew permission
        script: chmod +x ./gradlew
      - name: Build release APK
        script: ./gradlew assembleRelease
      - name: Show generated APK path
        script: find . -name "*.apk"
    artifacts:
      - build/app/outputs/**/*.apk