workflows:
  android-release:
    name: Build APK for Gauging App
    max_build_duration: 15
    environment:
      java: 17
    scripts:
      - name: Make gradlew executable
        script: chmod +x gradlew
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
