# codemagic.yaml
workflows:
  android-release:
    name: Build gauging APK
    max_build_duration: 15
    environment:
      android_signing:
        keystore_reference: "release-keystore"
      vars:
        PACKAGE_NAME: "com.example.gauging"
      flutter: false
      java: 17
    scripts:
      - name: Build APK
        script: |
          cd app
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
